name: Dev

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request_target:
    branches:
      - release/**
      - hotfix/**
      - develop
      - main
    types:
      - synchronize
      - opened
      - reopened
      - unlocked
  workflow_dispatch:

env:
  HELM_CHART_RELATIVE_LOCATION: gitops/images/eve
  APP_NAME: eve

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: build
        shell: bash
        run: |
          echo "checks"
          echo ${{ github.event.repository.name }}

  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push' || github.ref == 'refs/heads/release' && github.event_name == 'push' || github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # Fetches entire history, so we can analyze commits since last tag.
          fetch-depth: 0
      - name: build
        shell: bash
        run: |
          mkdir ./eve/
          docker run lfedge/eve:7.4.1-kvm-amd64 installer_raw > ./eve/ades.raw 
          echo "blank space"
          echo "blank space"
      - name: Archive eve-os artifacts
        uses: actions/upload-artifact@v2
        with:
          name: eve-charts
          path: ./eve/
  container-test-job:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ubuntu
      env:
        NODE_ENV: development
      ports:
        - 80
      options: --cap-add SYS_ADMIN --privileged
    steps:
      - name: Download all workflow artifacts
        uses: actions/download-artifact@v2
        with:
          path: ./eve/
      - name: Check for dockerenv file
        run: |
          loop_device_prod=$(losetup -f -P "./eve/eve-charts/ades.raw" --show)
          lsblk -f
          echo $loop_device_prod
          eve_partition_prod=$loop_device_prod'p4'
          mkdir ./mount_prod
          mount $eve_partition_prod ./mount_prod
          cat /mount_prod/server