name: Dev

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request_target:
    branches:
      - release/**
      - hotfix/**
      - develop
      - main
    types:
      - synchronize
      - opened
      - reopened
      - unlocked
  workflow_dispatch:

env:
  HELM_CHART_RELATIVE_LOCATION: gitops/images/eve
  APP_NAME: eve

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: build
        shell: bash
        run: |
          echo "checks"
          echo ${{ github.event.repository.name }}

  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push' || github.ref == 'refs/heads/release' && github.event_name == 'push' || github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # Fetches entire history, so we can analyze commits since last tag.
          fetch-depth: 0
      - name: build
        shell: bash
        run: |
          hostname
          echo "blank space"
          echo "blank space"
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:14.16
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - /dev/loop2:/dev/loop2
    steps:
      - name: Check for dockerenv file
        run: |
          hostname
          echo "hola dentro de container"
