name: Dev

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request_target:
    branches:
      - release/**
      - hotfix/**
      - develop
      - main
    types:
      - synchronize
      - opened
      - reopened
      - unlocked
env:
  HELM_CHART_RELATIVE_LOCATION: charts/

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: build
        shell: bash
        run: |
          echo "checks"
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push' || github.ref == 'refs/heads/release' && github.event_name == 'push' || github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: build
        shell: bash
        run: |
          echo "build"
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # Fetches entire history, so we can analyze commits since last tag.
          fetch-depth: 0
      - name: Archive eve-os artifacts
        if: github.event.inputs.tags || 
            github.ref == 'refs/heads/main' || 
            github.ref == 'refs/heads/release' || 
            github.ref == 'refs/heads/develop'
        uses: actions/upload-artifact@v2
        with:
          name: eve-charts
          path: ${{ env.HELM_CHART_RELATIVE_LOCATION }}
  create-sandbox-release:
    if: ${{ github.ref == 'refs/heads/develop' && github.event_name == 'push' }}
    needs: [build]   
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Download all workflow artifacts
        uses: actions/download-artifact@v2
        with:
          path: ${{ env.HELM_CHART_RELATIVE_LOCATION }}

      - name: Create Release Artifact
        run: |
          zip -r ${{ env.HELM_CHART_RELATIVE_LOCATION }}/eve-charts.zip ${{ env.HELM_CHART_RELATIVE_LOCATION }}
      - name: Checkout repository with entire history
        uses: actions/checkout@v2
        with:
          # Fetches entire history, so we can analyze commits since last tag.
          fetch-depth: 0

      - name: Bump version and push tag
        id: create_tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: master
          PRERELEASE_SUFFIX: development
          DRY_RUN: false

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.new_tag || github.event.inputs.tags }}
          release_name: Release ${{ steps.create_tag.outputs.new_tag || github.event.inputs.tags }}
          body: Change logs temporarily disabled.
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.HELM_CHART_RELATIVE_LOCATION }}
          asset_name: ${{ env.HELM_CHART_RELATIVE_LOCATION }}
          asset_content_type: application/zip

  create-nonprod-release:
    if: ${{ github.ref == 'refs/heads/release' && github.event_name == 'push' }}
    needs: [build]   
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Download all workflow artifacts
        uses: actions/download-artifact@v2
        with:
          path: ${{ env.HELM_CHART_RELATIVE_LOCATION }}

      - name: Create Release Artifact
        run: |
          zip -r ../${{ env.HELM_CHART_RELATIVE_LOCATION }}.zip ${{ env.HELM_CHART_RELATIVE_LOCATION }}
      - name: Checkout repository with entire history
        uses: actions/checkout@v2
        with:
          # Fetches entire history, so we can analyze commits since last tag.
          fetch-depth: 0

      - name: Bump version and push tag
        id: create_tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: master
          PRERELEASE_SUFFIX: prerelease
          DRY_RUN: false

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.new_tag || github.event.inputs.tags }}
          release_name: Release ${{ steps.create_tag.outputs.new_tag || github.event.inputs.tags }}
          body: Change logs temporarily disabled.
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.HELM_CHART_RELATIVE_LOCATION }}
          asset_name: ${{ env.HELM_CHART_RELATIVE_LOCATION }}
          asset_content_type: application/zip

  create-production-release:
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    needs: [build]   
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Download all workflow artifacts
        uses: actions/download-artifact@v2
        with:
          path: ${{ env.HELM_CHART_RELATIVE_LOCATION }}

      - name: Create Release Artifact
        run: |
          zip -r ../${{ env.HELM_CHART_RELATIVE_LOCATION }} ${{ env.HELM_CHART_RELATIVE_LOCATION }}
      - name: Checkout repository with entire history
        uses: actions/checkout@v2
        with:
          # Fetches entire history, so we can analyze commits since last tag.
          fetch-depth: 0

      - name: Bump version and push tag
        id: create_tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: master
          PRERELEASE_SUFFIX: prerelease
          DRY_RUN: false

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.new_tag || github.event.inputs.tags }}
          release_name: Release ${{ steps.create_tag.outputs.new_tag || github.event.inputs.tags }}
          body: Change logs temporarily disabled.
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.HELM_CHART_RELATIVE_LOCATION }}
          asset_name: ${{ env.HELM_CHART_RELATIVE_LOCATION }}
          asset_content_type: application/zip
