# name: create release

# on:
#   push:
#     branches:
#       - '**'
#     tags-ignore:
#       - '**'
#   pull_request_target:
#     branches:
#       - release/**
#       - hotfix/**
#       - develop
#       - main
#     types:
#       - synchronize
#       - opened
#       - reopened
#       - unlocked
# jobs:
#   build:
#     name: Create Release
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Create Release
#         id: create_release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#         with:
#           tag_name: "v0.0.0"
#           release_name: Release v0.0.0
#           body: |
#             Changes in this Release
#             - Initial Commit
#           draft: false
#           prerelease: false

name: Bump version
on:
  push:
    branches:
      - main
      - release
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_BRANCHES : main